Error handling
vocascan/vocascan-server pull request #32
Opened 2021-04-03 08:36 UTC by noctera

| Status  | Type  | Env Vars Change |
| :---: | :---: | :---: |
| Ready | Hotfix | No |
## Description

I've added error handling to the existing functions so that the server doesn't crash if the user sends an incorrect value in their request.

- Deleted unnecessary response output
- Added drawer stage to vocabulary output

## Motivation and Context

These changes are required so that the server does not crash in the event of incorrect requests.

## How Has This Been Tested?

has not been tested yet

## Screenshots / GIFs (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking change which cleans up / improves existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added unit tests to code changes that make sense.
- [x] I have considered the accessibility of my changes (i.e. did I add proper content descriptions to images, or run my changes with talkback enabled?)
- [x] I have documented my code if needed

2021-04-04 21:28 UTC, luwol03 requested changes
If we execute methods of the http response in the service provider, I find it a bit messy, because the provider shouldn't have anything to do with the controller. I think the provider should easily work with e.g. graphql. And if we do it this way, we get errors because you can no longer write a response that has already been sent. You get an error from express see below.

![unknown.png](https://user-images.githubusercontent.com/60048565/113521806-200b9980-959c-11eb-85ca-bb397bd679a2.png)

I think it's a better way to return an array from the service provider with an error object or null and the actual response from the provider. And so we made it a little bit more abstract and not have to use the response inside the provider. I can show you tomorrow how I do this in my project.

2021-04-04 21:28 UTC, luwol03 commented on app/Controllers/LanguagePackageController.js
can we remove that empty line after the comment?

2021-04-04 21:28 UTC, luwol03 commented on app/Controllers/VocabularyController.js
>      formatted.translations = translations;
we can remove the formatted variable, because this is only an reference to the original object and not a copy.

2021-04-04 21:28 UTC, luwol03 commented on app/Services/GroupServiceProvider.js
> +    .then((deletedGroup) => {
Use async and await

2021-04-04 21:28 UTC, luwol03 commented on app/Services/GroupServiceProvider.js
> +    .then((updatedGroup) => {
Use async and await

2021-04-04 21:28 UTC, luwol03 commented on app/Services/LanguagePackageServiceProvider.js
> +    .then((deletedLanguagePackage) => {
Use async and await

2021-04-04 21:28 UTC, luwol03 commented on app/Services/LanguagePackageServiceProvider.js
> +    .then((updatedLanguagePackage) => {
Use async and await

2021-04-04 21:28 UTC, luwol03 commented on app/Services/QueryServiceProvider.js
> +    const number = await await VocabularyCard.count({
One await is enough

2021-04-04 21:28 UTC, luwol03 commented on app/Services/VocabularyServiceProvider.js
> +    .then((deletedVocabularyCard) => {
Use async and await

2021-04-06 16:57 UTC, noctera commented
Added error handling to every function. I will specify and improve the error messages in a later PR

2021-04-08 16:26 UTC, luwol03 requested changes

2021-04-08 16:26 UTC, luwol03 commented on app/Controllers/LanguagePackageController.js
> +  const [error] = await destroyLanguagePackage(userId, languagePackageId);
throw `APIError` inside of service provider.

2021-04-08 16:26 UTC, luwol03 commented on app/Controllers/LanguagePackageController.js
> +  const [error] = await updateLanguagePackage(req.body, userId, languagePackageId);
throw `APIError` inside of service provider.

2021-04-08 16:26 UTC, luwol03 commented on app/Controllers/StatsController.js
> +  logs.inactiveVocabulary = await getNumberOfInactiveVocabulary(userId);
can we calcualte this in parallel with `Promise.all`?

2021-04-08 16:26 UTC, luwol03 commented on app/Services/AuthServiceProvider.js
>      return false;
throw `APIError` here.

2021-04-08 16:26 UTC, luwol03 commented on app/Services/LanguagePackageServiceProvider.js
> +  if (counter === 0) {
add a new line before this

2021-04-08 16:26 UTC, luwol03 commented on app/Services/StatsServiceProvider.js
> +async function getNumberOfActiveVocabulary(userId) {
can we move the active in all functions in this provider into an argument, so we only need 3 functions?

2021-04-08 16:26 UTC, luwol03 commented on package-lock.json
> +  "lockfileVersion": 1,
use npm7

2021-04-08 16:26 UTC, luwol03 commented on server.js
> +});
move this above of the error middlewares

2021-04-08 21:38 UTC, noctera commented on app/Services/AuthServiceProvider.js
>      return false;
APIError is getting returned by the validateRegister() function

```
  if (!validateAuth(req, res)) {
    throw new ApiError(httpStatus.BAD_REQUEST, 'missing parameter');
  }
  ```
additional error handling would be duplicate.

2021-04-10 08:22 UTC, noctera commented on app/Middleware/ProtectMiddleware.js
> +const ProtectMiddleware = catchAsync(async (req, _res, next) => {
why did you use _res instead of res?

2021-04-13 11:39 UTC, luwol03 approved these changes

2021-04-13 16:42 UTC, merged